version: '3'
services:
  nginx:
    image: 'nginx:latest'
    container_name: nginx-test
    depends_on:
      - node
      - php
    volumes:
      - './.docker/nginx/conf:/etc/nginx/conf.d'
      - '.:/var/www/app'
      - './.docker/nginx/logs:/var/log/nginx'
    environment:
      - TZ=Europe/Moscow
    networks:
      development:
        aliases:
          - webpack.test
      proxy-pass:
        aliases:
          - nginx
  node:
    image: 'webpack-test-node'
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile
    container_name: node-test
    command: ["webpack-dev-server"]
    volumes:
      - '.:/var/www/app'
    environment:
      - TZ=Europe/Moscow
    networks:
      proxy-pass:
        aliases:
          - node
  php:
    image: php:7.2-fpm-alpine
    container_name: php-fpm-test
    volumes:
      - '.:/var/www/app'
    environment:
      - TZ=Europe/Moscow
    networks:
      proxy-pass:
        aliases:
          - php-fpm
networks:
  proxy-pass:
  development:
    external:
      name: develope